//===- GAAOps.cpp - Handshake MLIR Operations -----------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file contains the declaration of the GAA operations struct.
//
//===----------------------------------------------------------------------===//
#include "circt/Dialect/GAA/GAAOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/HW/HWOps.h"

using namespace mlir;
using namespace circt;
using namespace gaa;

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/GAA/GAA.cpp.inc"
